import {pavingRing} from "../../lib/native-extra-calculators";
// Coordinates below use the same native geometry used for the numeric results.
export function drawNativeExtra(ctx:CanvasRenderingContext2D,w:number,h:number,kind:string,v:Record<string,number>,unit:string){
 ctx.clearRect(0,0,w,h);ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);if(w<80||h<80)return;
 const text=(s:string,x:number,y:number,color="#222")=>{ctx.fillStyle=color;ctx.font="12px Verdana";ctx.textAlign="center";ctx.fillText(s,x,y);};
 const fmt=(n:number)=>`${new Intl.NumberFormat("en-NZ",{maximumFractionDigits:2}).format(n)} ${unit}`;
 const line=(x:number,y:number,x2:number,y2:number,color="#333")=>{ctx.strokeStyle=color;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();};
 const poly=(pts:number[][],fill="#ddd")=>{ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle="#444";ctx.stroke();};
 if(v.nativeRing){const g=pavingRing(v);if(!g)return;
  if(kind==="nativeringtemplate"){const s=Math.min((w-100)/g.outer,(h-100)/v.unitDepth),x=(w-g.outer*s)/2,y=(h-v.unitDepth*s)/2,inset=(g.outer-g.inner)/2;poly([[x,y],[x+g.outer*s,y],[x+(g.outer-inset)*s,y+v.unitDepth*s],[x+inset*s,y+v.unitDepth*s]]);text(`Outer ${fmt(g.outer)}`,w/2,y-18);text(`Inner ${fmt(g.inner)}`,w/2,y+v.unitDepth*s+25);text(`Depth ${fmt(v.unitDepth)} · miter ${(180/v.count).toFixed(3)}°`,w/2,h-15);return {unitsPerPixel:1/s,unit};}
  const iso=kind.endsWith("3d"),s=Math.min((w-80)/v.diameter,(h-100)/(v.diameter*(iso?.6:1)+v.paverThickness));
  const project=(x:number,y:number,z=0)=>[w/2+x*s,h/2+y*s*(iso?.6:1)-z*s];
  for(let i=0;i<v.count;i++){const a=i*2*g.half,c=Math.cos(a),sn=Math.sin(a),base=[[-g.outer/2,g.apothem],[-g.inner/2,g.innerApothem],[g.inner/2,g.innerApothem],[g.outer/2,g.apothem]],face=base.map(([x,y])=>[x*c-y*sn,x*sn+y*c]);if(iso)for(let j=0;j<4;j++){const p=face[j],q=face[(j+1)%4];poly([project(...p as [number,number]),project(...q as [number,number]),project(q[0],q[1],v.paverThickness),project(p[0],p[1],v.paverThickness)],"#a9a9a9");}poly(face.map(([x,y])=>project(x,y,iso?v.paverThickness:0)),"#d8cab7");}
  text(`Outside corner diameter ${fmt(v.diameter)}`,w/2,24);text(`${v.count} pavers · side joint ${fmt(v.joint)}`,w/2,h-18);return iso?undefined:{unitsPerPixel:1/s,unit};
 }
 if(v.nativePipe){const s=Math.min((w-120)/v.run,(h-110)/v.finishDepth),x=(w-v.run*s)/2,y=45,ex=x+v.run*s,ey=y+v.finishDepth*s;line(x,y,ex,y,"#888");line(x,y+v.startInvert*s,ex,ey,"#0276fd");const detailed=kind==="nativedrainprofile",stride=Math.max(1,Math.ceil(v.intervals/(detailed?6:3)));for(let i=0;i<=v.intervals;i++){if(i%stride!==0&&i!==v.intervals)continue;const station=i===v.intervals?v.run:i*v.spacing;if(i>0&&i<v.intervals&&((v.run-station)*s<85||station*s<85))continue;const px=x+station*s,py=y+(v.startInvert+station/v.grade)*s;line(px,y,px,py,"#bbb");text(fmt(station),px,y-12);text(fmt(v.startInvert+station/v.grade),px,py+20,"#00f");}text(`1 in ${v.grade} · total fall ${fmt(v.fall)}`,w/2,h-22);return {unitsPerPixel:1/s,unit};}
 if(v.nativeRoofDrain){const detail=kind==="nativedrainprofile",run=detail?v.spacing:v.eave,s=Math.min((w-100)/run,(h-100)/v.catchment),x=(w-run*s)/2,y=(h-v.catchment*s)/2;ctx.fillStyle="#eee";ctx.fillRect(x,y,run*s,v.catchment*s);ctx.strokeStyle="#777";ctx.strokeRect(x,y,run*s,v.catchment*s);const n=detail?1:v.outlets,stride=Math.max(1,Math.ceil(n/100));for(let i=0;i<n;i+=stride){const px=x+(i+.5)*v.spacing*s;ctx.fillStyle="#0276fd";ctx.beginPath();ctx.arc(px,y+v.catchment*s,4,0,Math.PI*2);ctx.fill();if(n<=12)text(String(i+1),px,y+v.catchment*s+18);if(i>0)line(x+i*v.spacing*s,y,x+i*v.spacing*s,y+v.catchment*s,"#bbb");}text(`${detail?"Tributary width":"Eave"} ${fmt(run)}`,w/2,y-18);text(`${v.outlets} outlets · ${new Intl.NumberFormat("en-NZ",{maximumFractionDigits:3}).format(v.flow/v.outlets)} L/s each`,w/2,h-15);if(stride>1)text("Diagram samples outlets; complete positions are in the set-out list",w/2,15);return {unitsPerPixel:1/s,unit};}
}
