/**
 * GENERATED by scripts/make-demo-voiceover.mjs from ./demo-voiceover.ts. Do not edit.
 * Per video: each chapter's length and each line's [start, end] in seconds
 * from the chapter's start, measured from the spoken audio (kokoro af_heart).
 */
export const VOICEOVER_TIMINGS = {
  "demo": {
    "scriptHash": "cad44051fa547482",
    "totalSeconds": 68.866,
    "chapters": [
      {
        "id": "intro",
        "seconds": 8.767,
        "lines": [
          [
            0.45,
            1.774
          ],
          [
            2.074,
            8.165
          ]
        ]
      },
      {
        "id": "talk",
        "seconds": 13.133,
        "lines": [
          [
            0.45,
            4.027
          ],
          [
            4.327,
            7.163
          ],
          [
            7.463,
            12.527
          ]
        ]
      },
      {
        "id": "draft",
        "seconds": 11.933,
        "lines": [
          [
            0.45,
            4.207
          ],
          [
            4.507,
            11.313
          ]
        ]
      },
      {
        "id": "check",
        "seconds": 7.933,
        "lines": [
          [
            0.45,
            2.704
          ],
          [
            3.004,
            5.42
          ],
          [
            5.72,
            7.313
          ]
        ]
      },
      {
        "id": "send",
        "seconds": 11.9,
        "lines": [
          [
            0.45,
            2.282
          ],
          [
            2.582,
            8.727
          ],
          [
            9.027,
            11.279
          ]
        ]
      },
      {
        "id": "invoice",
        "seconds": 9.067,
        "lines": [
          [
            0.45,
            4.482
          ],
          [
            4.782,
            8.439
          ]
        ]
      },
      {
        "id": "end",
        "seconds": 6.133,
        "lines": [
          [
            0.45,
            2.399
          ],
          [
            2.699,
            5.523
          ]
        ]
      }
    ]
  },
  "social": {
    "scriptHash": "287ae09515c26224",
    "totalSeconds": 22.267,
    "chapters": [
      {
        "id": "hook",
        "seconds": 2.567,
        "lines": [
          [
            0.25,
            2.199
          ]
        ]
      },
      {
        "id": "talk",
        "seconds": 3,
        "lines": [
          [
            0.25,
            1.698
          ]
        ]
      },
      {
        "id": "draft",
        "seconds": 3.6,
        "lines": [
          [
            0.25,
            3.24
          ]
        ]
      },
      {
        "id": "check",
        "seconds": 3.133,
        "lines": [
          [
            0.25,
            2.778
          ]
        ]
      },
      {
        "id": "send",
        "seconds": 3,
        "lines": [
          [
            0.25,
            1.807
          ]
        ]
      },
      {
        "id": "invoice",
        "seconds": 3,
        "lines": [
          [
            0.25,
            1.889
          ]
        ]
      },
      {
        "id": "end",
        "seconds": 3.967,
        "lines": [
          [
            0.25,
            1.736
          ],
          [
            1.936,
            3.613
          ]
        ]
      }
    ]
  },
  "tour": {
    "scriptHash": "9e4353a754ad756a",
    "totalSeconds": 98.133,
    "chapters": [
      {
        "id": "intro",
        "seconds": 7.533,
        "lines": [
          [
            0.45,
            2.391
          ],
          [
            2.691,
            6.929
          ]
        ]
      },
      {
        "id": "request",
        "seconds": 12.2,
        "lines": [
          [
            0.45,
            5.136
          ],
          [
            5.436,
            11.6
          ]
        ]
      },
      {
        "id": "talk",
        "seconds": 13.133,
        "lines": [
          [
            0.45,
            4.027
          ],
          [
            4.327,
            7.163
          ],
          [
            7.463,
            12.527
          ]
        ]
      },
      {
        "id": "draft",
        "seconds": 11.933,
        "lines": [
          [
            0.45,
            4.207
          ],
          [
            4.507,
            11.313
          ]
        ]
      },
      {
        "id": "supplier",
        "seconds": 10.067,
        "lines": [
          [
            0.45,
            3.53
          ],
          [
            3.83,
            9.447
          ]
        ]
      },
      {
        "id": "check",
        "seconds": 7.933,
        "lines": [
          [
            0.45,
            2.704
          ],
          [
            3.004,
            5.42
          ],
          [
            5.72,
            7.313
          ]
        ]
      },
      {
        "id": "send",
        "seconds": 11.9,
        "lines": [
          [
            0.45,
            2.282
          ],
          [
            2.582,
            8.727
          ],
          [
            9.027,
            11.279
          ]
        ]
      },
      {
        "id": "timesheet",
        "seconds": 7.7,
        "lines": [
          [
            0.45,
            3.212
          ],
          [
            3.512,
            7.071
          ]
        ]
      },
      {
        "id": "invoice",
        "seconds": 9.067,
        "lines": [
          [
            0.45,
            4.482
          ],
          [
            4.782,
            8.439
          ]
        ]
      },
      {
        "id": "end",
        "seconds": 6.667,
        "lines": [
          [
            0.45,
            2.399
          ],
          [
            2.699,
            6.036
          ]
        ]
      }
    ]
  }
} as const;
