/**
 * GENERATED by scripts/make-demo-voiceover.mjs from ./demo-voiceover.ts. Do not edit.
 * Each chapter's length and each line's [start, end] in seconds from the
 * chapter's start, measured from the spoken audio (kokoro af_heart).
 */
export const VOICEOVER_TIMING = {
  scriptHash: "2a403a1a98b4d516",
  totalSeconds: 68.866,
  chapters: [
    {
      "id": "intro",
      "seconds": 8.767,
      "lines": [
        [
          0.45,
          1.774
        ],
        [
          2.074,
          8.165
        ]
      ]
    },
    {
      "id": "talk",
      "seconds": 13.133,
      "lines": [
        [
          0.45,
          4.027
        ],
        [
          4.327,
          7.163
        ],
        [
          7.463,
          12.527
        ]
      ]
    },
    {
      "id": "draft",
      "seconds": 11.933,
      "lines": [
        [
          0.45,
          4.207
        ],
        [
          4.507,
          11.313
        ]
      ]
    },
    {
      "id": "check",
      "seconds": 7.933,
      "lines": [
        [
          0.45,
          2.704
        ],
        [
          3.004,
          5.42
        ],
        [
          5.72,
          7.313
        ]
      ]
    },
    {
      "id": "send",
      "seconds": 11.9,
      "lines": [
        [
          0.45,
          2.282
        ],
        [
          2.582,
          8.727
        ],
        [
          9.027,
          11.279
        ]
      ]
    },
    {
      "id": "invoice",
      "seconds": 9.067,
      "lines": [
        [
          0.45,
          4.482
        ],
        [
          4.782,
          8.439
        ]
      ]
    },
    {
      "id": "end",
      "seconds": 6.133,
      "lines": [
        [
          0.45,
          2.399
        ],
        [
          2.699,
          5.523
        ]
      ]
    }
  ],
} as const;
