import type { Icon } from "@phosphor-icons/react";
import {
  AddressBook,
  Bug,
  CalendarBlank,
  ChatCircleDots,
  Compass,
  CreditCard,
  FilePdf,
  Gauge,
  Lifebuoy,
  Pulse,
  QrCode,
  Robot,
  Scroll,
  ShieldCheck,
  SlidersHorizontal,
  Storefront,
  Tag,
  UserCircle,
  UsersThree,
} from "@phosphor-icons/react/dist/ssr";
import type { MoreItemId } from "../_lib/menu";

/** One icon per More row, shared by the More screen and the account sheet. */
export const MORE_ICON: Readonly<Record<MoreItemId, Icon>> = {
  clients: AddressBook,
  prices: Tag,
  calendar: CalendarBlank,
  qr: QrCode,
  business: Storefront,
  rates: SlidersHorizontal,
  payments: CreditCard,
  account: UserCircle,
  team: UsersThree,
  help: Lifebuoy,
  tour: Compass,
  feedback: ChatCircleDots,
  privacy: ShieldCheck,
  terms: Scroll,
  drawings: FilePdf,
  agents: Robot,
  debug: Bug,
  monitor: Pulse,
  ops: Gauge,
};
