import "server-only";
import * as React from "react";
import {Html,Head,Preview,Body,Container,Section,Heading,Text,Button,Hr,render,toPlainText} from "react-email";
type BusinessEmailArgs={kind:"quote"|"invoice"|"request";businessName:string;clientName:string;number?:string;total?:string;dueDate?:string;paymentInstructions?:string|null;contact?:string;site?:string|null;description?:string;actionUrl?:string};
export async function renderBusinessEmail(args:BusinessEmailArgs){
  if(args.actionUrl){const url=new URL(args.actionUrl);if(!["https:","http:"].includes(url.protocol))throw new Error("Email action must use an HTTP or HTTPS URL.");}
  const title=args.kind==="quote"?`Quote ${args.number}`:args.kind==="invoice"?`Invoice ${args.number}`:"New quote request";
  const summary=args.kind==="request"?`${args.clientName} has requested a quote.`:`${title} from ${args.businessName}${args.total?` · ${args.total}`:""}`;
  const html=await render(<Html lang="en"><Head/><Preview>{summary}</Preview><Body style={{backgroundColor:"#f3f3ef",fontFamily:"Arial, Helvetica, sans-serif",color:"#161616",margin:0,padding:"24px 8px"}}><Container style={{maxWidth:"560px",backgroundColor:"#ffffff",borderRadius:8,overflow:"hidden"}}><Section style={{backgroundColor:"#171717",padding:"24px"}}><Text style={{color:"#ff5f15",fontSize:12,fontWeight:700,letterSpacing:"2px",margin:"0 0 12px"}}>TRADIES2QUOTE</Text><Heading as="h1" style={{color:"#ffffff",fontSize:26,lineHeight:"32px",margin:0}}>{title}</Heading><Text style={{color:"#dddddd",margin:"10px 0 0"}}>{args.businessName}</Text></Section><Section style={{padding:"24px"}}>
    <Text>{args.kind==="request"?`New request from ${args.clientName}`:`Hi ${args.clientName},`}</Text>
    {args.kind==="request"?<><Text><strong>Contact:</strong> {args.contact||"not given"}<br/><strong>Site:</strong> {args.site||"not given"}</Text><Heading as="h2" style={{fontSize:17}}>What they want</Heading><Text style={{backgroundColor:"#f3f3ef",padding:16}}>{(args.description??"").split("\n").map((line,index)=><span key={index}>{line}<br/></span>)}</Text><Text>A draft quote is being prepared on your account. Review it, set your rates, and send it when you are ready.</Text></>:<><Text>Here is your {args.kind} from <strong>{args.businessName}</strong>.</Text><Text style={{fontSize:32,fontWeight:700,lineHeight:"40px",margin:"20px 0 8px"}}>{args.total}</Text>{args.dueDate&&<Text style={{margin:"0 0 20px"}}>Due {args.dueDate}</Text>}<Text>The full {args.kind} PDF is attached.</Text></>}
    {args.paymentInstructions&&<Section style={{backgroundColor:"#f3f3ef",borderLeft:"4px solid #ff5f15",padding:"0 16px"}}><Heading as="h2" style={{fontSize:17}}>How to pay</Heading><Text>{args.paymentInstructions.split("\n").map((line,index)=><span key={index}>{line}<br/></span>)}</Text></Section>}
    {args.actionUrl&&<><Button href={args.actionUrl} style={{backgroundColor:"#ff5f15",color:"#171717",borderRadius:4,padding:"16px 24px",fontSize:16,fontWeight:700,margin:"16px 0"}}>{args.kind==="quote"?"Accept Quote":"Open the draft quote"}</Button><Text style={{fontSize:12,color:"#555555",overflowWrap:"anywhere"}}>If the button does not work, copy this link: {args.actionUrl}</Text></>}
    <Hr style={{borderColor:"#dddddd",margin:"24px 0"}}/><Text style={{fontSize:13,color:"#555555"}}>{args.kind==="request"?"You received this because your Tradies2Quote request link is switched on. Turn it off any time in Settings.":"If you have any questions, reply to this email."}</Text><Text style={{fontSize:13,color:"#555555"}}>— {args.businessName}</Text>
  </Section></Container></Body></Html>);
  return {html,text:toPlainText(html)};
}
