"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
type Template={id?:string;title:string;body:string};
/** `inApp` (from the server): in the iPhone app (App Store 3.1.3(f)) no plan name and no link to the plans page. */
export function TemplatesManager({inApp=false}:{inApp?:boolean}={}){const[items,setItems]=useState<Template[]>([]);const[enabled,setEnabled]=useState(false);const[edit,setEdit]=useState(false);const[loaded,setLoaded]=useState(false);const[form,setForm]=useState<Template>({title:'',body:''});const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/terms-templates');const d=await r.json();if(!r.ok)throw Error(d.error);setItems(d.templates);setEnabled(d.enabled);setEdit(d.canEdit);setLoaded(true);}catch(e){setError(e instanceof Error?e.message:'Please retry.');}}
 // Refresh state follows an asynchronous API response.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load();},[]);
 return <div className="mt-8 space-y-6">{error&&<p role="alert" className="text-red-300">{error}</p>}{notice&&<p role="status" className="text-green-300">{notice}</p>}{loaded&&!enabled&&(inApp?<section className="t2q-card-pro p-6"><p className="text-sm text-ink-300">Shared terms templates aren’t switched on for this account.</p></section>:<section className="t2q-card-pro p-6"><p className="mb-4 text-sm text-ink-300">Reusable team terms are included with Builder.</p><Link href="/app/upgrade?plan=builder" className="t2q-btn-primary-pro">View plans</Link></section>)}{edit&&<form className="t2q-card-pro space-y-4 p-6" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/terms-templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw Error(d.error);setForm({title:'',body:''});setNotice('Template saved.');await load();}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}}><label className="block text-sm">Template name<input required maxLength={100} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="mt-2 min-h-11 w-full rounded-xl border border-white/15 bg-black/20 px-3"/></label><label className="block text-sm">Your terms<textarea required rows={8} maxLength={20000} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 p-3"/></label><button disabled={busy} className="t2q-btn-primary-pro">{busy?'Saving…':'Save template'}</button>{form.id&&<button type="button" onClick={()=>setForm({title:'',body:''})} className="t2q-btn-ghost-pro ml-3">Cancel edit</button>}</form>}{items.map(t=><article key={t.id} className="t2q-card-pro p-6"><div className="flex justify-between gap-4"><h2 className="text-lg font-semibold">{t.title}</h2>{edit&&<button onClick={()=>setForm(t)} className="min-h-11 text-sm text-brand">Edit</button>}</div><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-ink-300">{t.body}</p></article>)}</div>;
}
