"use client";
import {useEffect,useState} from "react";
import {exportLocalBackup,importLocalBackup,observeLocalLibrary,removeLocalWorking,restoreLocalWorking} from "../lib/local-db";
import type {DeviceWorking as Record} from "../lib/device-working";
import {BackupStatus} from "./BackupSync";
function download(data:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function DeviceWorking(){
  const [records,setRecords]=useState<Record[]>([]),[error,setError]=useState(""),[loaded,setLoaded]=useState(false),[removed,setRemoved]=useState<Awaited<ReturnType<typeof removeLocalWorking>>>(null),[notice,setNotice]=useState("");
  useEffect(()=>{const sub=observeLocalLibrary(data=>{setRecords(data.calculations);setLoaded(true);},e=>{setError(e instanceof Error?e.message:"Device storage is unavailable.");setLoaded(true);});return()=>sub.unsubscribe();},[]);
  async function remove(row:Record){try{setRemoved(await removeLocalWorking(row.id));setError("");}catch{setError("The calculation could not be removed.");}}
  async function undo(){if(!removed)return;try{await restoreLocalWorking(removed);setRemoved(null);}catch(e){setError(e instanceof Error?e.message:"The calculation could not be restored.");}}
  async function restore(file:File|undefined){if(!file)return;try{if(file.size>2_000_000)throw new Error("Choose a T2QCAL backup smaller than 2 MB.");const count=await importLocalBackup(JSON.parse(await file.text()));setError("");setNotice(`Restored ${count} calculations and merged job links. Newer device working was kept.`);}catch(e){setError(e instanceof Error?e.message:"The backup could not be restored.");}}
  async function backup(){try{download(await exportLocalBackup(),"t2qcal-working.json");}catch{setError("Your backup could not be exported.");}}
  function recovery(){try{download({calculations:localStorage.getItem("t2qcal.device-working.v1"),jobs:localStorage.getItem("t2qcal.device-jobs.v1")},"t2qcal-legacy-recovery.json");}catch{setError("The original browser storage could not be accessed.");}}
  return <main className="directory-page"><section className="page-intro"><div className="eyebrow">T2QCAL · On this device</div><h1>Your working</h1><p>Saved in this browser, available without signing in. Export calculations and jobs before clearing browser data. Plan PDFs have their own export in Plan takeoff.</p><div className="save-actions"><button className="directory-button" disabled={!loaded||!!error} onClick={()=>void backup()}>Export backup</button><label>Restore backup<input type="file" accept="application/json,.json" onChange={e=>{void restore(e.target.files?.[0]);e.target.value="";}}/></label><a href="/t2qcal/saved">Open account-saved working</a></div></section>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error} <button onClick={recovery}>Export original browser data for recovery</button></p>}{!loaded&&<p role="status">Loading your working…</p>}{removed&&<p role="status">Removed “{removed.row.name}”. <button onClick={()=>void undo()}>Undo</button></p>}{loaded&&!records.length&&!error&&<div className="empty-state"><h2>No device-saved working yet</h2><p>Open a calculator, enter your measurements and choose Save on this device.</p><a href="/t2qcal/calculators">Choose a calculator</a></div>}<div className="tool-grid">{records.map(row=><article className="save-working" key={row.id}><h2>{row.name}</h2><p>{row.snapshot.unit==="metric"?"Metric":"Imperial"} · {new Date(row.updated_at).toLocaleDateString()}</p><div className="save-actions"><a href={`/t2qcal/calculator/${row.snapshot.slug}#device=${row.id}`}>Open working</a><button onClick={()=>void remove(row)}>Remove from device</button></div></article>)}</div><BackupStatus/></main>;
}
