"use client";
import {useEffect,useState} from "react";
import {importDeviceWorking,readDeviceWorking,removeDeviceWorking,saveDeviceWorking,type DeviceWorking as Record} from "../lib/device-working";
export function DeviceWorking(){
  const [records,setRecords]=useState<Record[]>([]),[error,setError]=useState(""),[loaded,setLoaded]=useState(false),[removed,setRemoved]=useState<Record|null>(null);
  // Browser-owned storage is restored after hydration, once.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{try{setRecords(readDeviceWorking(localStorage));}catch(e){setError(e instanceof Error?e.message:"Device storage is unavailable.");}finally{setLoaded(true);}},[]);
  function remove(row:Record){try{removeDeviceWorking(localStorage,row.id);setRecords(readDeviceWorking(localStorage));setRemoved(row);setError("");}catch{setError("The calculation could not be removed.");}}
  function undo(){if(!removed)return;try{saveDeviceWorking(localStorage,removed);setRecords(readDeviceWorking(localStorage));setRemoved(null);}catch{setError("The calculation could not be restored.");}}
  async function restore(file:File|undefined){if(!file)return;try{if(file.size>2_000_000)throw new Error("Choose a T2QCAL backup smaller than 2 MB.");const count=importDeviceWorking(localStorage,JSON.parse(await file.text()));setRecords(readDeviceWorking(localStorage));setError("");setNotice(`Restored ${count} calculations. Newer working on this device was kept.`);}catch(e){setError(e instanceof Error?e.message:"The backup could not be restored.");}}
  const [notice,setNotice]=useState("");
  function backup(){const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,calculations:records},null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download="t2qcal-working.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <main className="directory-page"><section className="page-intro"><div className="eyebrow">T2QCAL · On this device</div><h1>Your working</h1><p>Saved in this browser, available without signing in. Keep an exported backup before clearing browser data.</p><div className="save-actions"><button className="directory-button" disabled={!records.length} onClick={backup}>Export backup</button><label>Restore backup<input type="file" accept="application/json,.json" onChange={e=>{void restore(e.target.files?.[0]);e.target.value="";}}/></label><a href="/t2qcal/saved">Open account-saved working</a></div></section>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}{!loaded&&<p role="status">Loading your working…</p>}{removed&&<p role="status">Removed “{removed.name}”. <button onClick={undo}>Undo</button></p>}{loaded&&!records.length&&!error&&<div className="empty-state"><h2>No device-saved working yet</h2><p>Open a calculator, enter your measurements and choose Save on this device.</p><a href="/t2qcal/calculators">Choose a calculator</a></div>}<div className="tool-grid">{records.map(row=><article className="save-working" key={row.id}><h2>{row.name}</h2><p>{row.snapshot.unit==="metric"?"Metric":"Imperial"} · {new Date(row.updated_at).toLocaleDateString()}</p><div className="save-actions"><a href={`/t2qcal/calculator/${row.snapshot.slug}#device=${row.id}`}>Open working</a><button onClick={()=>remove(row)}>Remove from device</button></div></article>)}</div></main>;
}
