"use client";
import {useEffect,useState} from "react";
import {Folder,Plus,CaretRight} from "@phosphor-icons/react";
import type {DeviceJobs} from "@/t2qcal/lib/device-jobs";
import {activateLocalJob,createLocalJob,observeLocalLibrary} from "@/t2qcal/lib/local-db";
import type {DeviceWorking} from "@/t2qcal/lib/device-working";
export function JobsScreen(){
 const [data,setData]=useState<DeviceJobs|null>(null),[records,setRecords]=useState<DeviceWorking[]>([]),[error,setError]=useState(""),[creating,setCreating]=useState(false),[name,setName]=useState(""),[client,setClient]=useState("");
 useEffect(()=>{const sub=observeLocalLibrary(value=>{setData(value.jobs);setRecords(value.calculations);},e=>setError(e instanceof Error?e.message:"Device storage is unavailable."));return()=>sub.unsubscribe();},[]);
 async function create(e:React.FormEvent){e.preventDefault();try{setData(await createLocalJob(name,client));setCreating(false);setName("");setClient("");setError("");}catch(e){setError(e instanceof Error?e.message:"Your job could not be saved.");}}
 async function activate(id:string|null){try{setData(await activateLocalJob(id));setError("");}catch(e){setError(e instanceof Error?e.message:"Your job could not be selected.");}}
 return <main className="native-page"><h1 className="native-heading">Jobs</h1><button className="native-row native-group" onClick={()=>setCreating(true)} disabled={!data}><Plus size={24} color="#ff5f15"/><span><strong>Start a job</strong></span></button><p className="native-footnote">A job keeps every calculation for one piece of work together. Select a job, then save your calculator working on this device to add it.</p>{error&&<p role="alert">{error}</p>}{creating&&<form className="native-group" style={{padding:20}} onSubmit={create}><label className="native-field">What the job is<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)} autoFocus/></label><label className="native-field">Client (optional)<input maxLength={120} value={client} onChange={e=>setClient(e.target.value)}/></label><div className="save-actions"><button className="directory-button" type="submit">Start</button><button type="button" onClick={()=>setCreating(false)}>Cancel</button></div></form>}
 {data?.jobs.length===0&&<section className="native-empty"><Folder size={48}/><h2>No jobs yet</h2><p>Start one before you measure, and keep your calculations together.</p></section>}
 {data?.jobs.map(job=>{const items=records.filter(r=>job.calculationIds.includes(r.id));return <section key={job.id}><h2 className="native-section-label">{job.id===data.activeId?"ADDING TO":"JOB"}</h2><div className="native-group"><button className="native-row" onClick={()=>activate(job.id===data.activeId?null:job.id)} aria-pressed={job.id===data.activeId}><Folder size={26} color="#ff5f15"/><span><strong>{job.name}</strong><small>{job.client?`${job.client} · `:""}{items.length} saved calculations</small><small>{job.id===data.activeId?"Tap to stop adding to this job":"Tap to add new calculations to this job"}</small></span></button>{items.map(item=><a className="native-row" key={item.id} href={`/t2qcal/calculator/${item.snapshot.slug}#device=${item.id}`}><span><strong>{item.name}</strong><small>{new Date(item.updated_at).toLocaleDateString()} · {item.snapshot.unit}</small></span><CaretRight size={16}/></a>)}</div></section>;})}
 <p className="native-footnote">Jobs here are stored in this browser. They do not yet import or sync the jobs saved on your iPhone.</p><a className="native-row native-group" href="/t2qcal/device"><span><strong>All saved working</strong><small>Open calculations and manage device backups.</small></span><CaretRight size={16}/></a></main>;
}
