import {describe,it,expect} from 'vitest';
import nativeCases from './fixtures/native-stairs.json';
import {calculateStairs} from './calculations';
// Generated by executing the native StairGeometry.swift implementation, not a JS copy.
// Includes metric/inch equivalents, 2–60 risers and three different goings.
describe('native T2QCAL stair geometry compatibility',()=>{
 for(const [index,row] of nativeCases.entries())it(`matches native reference ${index+1}`,()=>{
  const result=calculateStairs(row.totalRise,row.preferredRise,row.run,row.floor,row.headroom);
  for(const key of ['risers','treads','totalRun','angle','bridge','notchDepth','stringer','stockGuide','openingRun'] as const){
   expect(result[key]).toBeCloseTo(row[key],8);
  }
 });
});
