// Formula port of the native DrainageGeometry and PavingRingGeometry models.
import catalog from "./native-catalog.json";
import type {VerifiedDefinition,CalculatorField,VerifiedUnit} from "./verified-calculators";
export function pavingRing(v:Record<string,number>){const radius=v.diameter/2,half=Math.PI/v.count,angle=half-Math.asin(v.joint/v.diameter),apothem=radius*Math.cos(angle),outer=2*radius*Math.sin(angle),inner=outer-2*v.unitDepth*Math.tan(half);if(!(angle>0&&apothem>v.unitDepth&&inner>0))return null;return {radius,half,apothem,outer,inner,innerApothem:apothem-v.unitDepth,area:(outer+inner)*v.unitDepth/2};}
const ceilStable=(v:number)=>Math.max(1,Math.ceil(v-8*Number.EPSILON*Math.max(1,Math.abs(v))));
export function nativeExtraDefinition(slug:string):VerifiedDefinition|null{
 if(!["pipe-fall","spouting-downpipes","paving-ring"].includes(slug))return null;
 const tool=catalog.tools.find(t=>t.slug===slug)!;
 const fields=tool.fields.map(f=>({...f,kind:f.kind==="integer"?"count":f.kind})) as CalculatorField[];
 const number=(n:number,d=3)=>new Intl.NumberFormat("en-NZ",{maximumFractionDigits:d}).format(n);
 const len=(n:number,u:VerifiedUnit)=>`${number(n)} ${u==="metric"?"mm":"in"}`;
 return {title:tool.name,note:tool.summary,fields,diagram:slug==="paving-ring"?"nativering":"nativedrain",showsAssembly:slug==="paving-ring",sheets:slug==="paving-ring"?[{label:"Ring plan",diagram:"nativering"},{label:"Paver template",diagram:"nativeringtemplate"}]:[{label:slug==="pipe-fall"?"Pipe fall":"Catchment plan",diagram:"nativedrain"},{label:slug==="pipe-fall"?"Invert profile":"Outlet set-out",diagram:"nativedrainprofile"}],compute(v,u){
 if(slug==="pipe-fall"){const spacing=v.marks*1000/(u==="metric"?1:25.4),ratio=v.run/spacing;if(!Number.isFinite(ratio)||ratio>9999+8*Number.EPSILON*9999)return {errors:["Use a larger peg spacing; the set-out supports up to 10,000 stations."],results:[]};const intervals=ceilStable(ratio),fall=v.run/v.grade;return {diagramValues:{...v,nativePipe:1,fall,finishDepth:v.startInvert+fall,spacing,intervals},results:[{label:"Total fall",value:len(fall,u),primary:true},{label:"Finish invert depth",value:len(v.startInvert+fall,u)},{label:u==="metric"?"Fall per metre":"Fall per foot",value:len((u==="metric"?1000:12)/v.grade,u)},{label:"Grade",value:`1 : ${number(v.grade)}`},{label:"Grade percent",value:`${number(100/v.grade)}%`},{label:"Slope angle",value:`${number(Math.atan(1/v.grade)*180/Math.PI)}°`},{label:"Pipe length",value:len(Math.hypot(v.run,fall),u)},{label:"Set-out stations",value:String(intervals+1)}],marks:Array.from({length:intervals+1},(_,i)=>{const x=i===intervals?v.run:i*spacing;return `${i+1} · distance ${len(x,u)} · invert depth ${len(v.startInvert+x/v.grade,u)}`;})};}
 if(slug==="spouting-downpipes"){const mm=u==="metric"?1:25.4,area=(v.eave*mm/1000)*(v.catchment*mm/1000),flow=area*v.intensity/3600,ratio=flow/v.capacity;if(!Number.isFinite(ratio)||ratio>10000+8*Number.EPSILON*10000)return {errors:["This layout supports up to 10,000 outlets. Check rainfall and outlet capacity."],results:[]};const outlets=ceilStable(ratio),spacing=v.eave/outlets;return {diagramValues:{...v,nativeRoofDrain:1,flow,outlets,spacing},results:[{label:"Outlets required",value:String(outlets),primary:true},{label:"Horizontal catchment area",value:`${number(area)} m²`},{label:"Design runoff",value:`${number(flow)} L/s`},{label:"Flow per outlet",value:`${number(flow/outlets)} L/s`},{label:"Tributary width",value:len(spacing,u)},{label:"End setback",value:len(spacing/2,u)},{label:"Capacity basis",value:"User-supplied outlet capacity; complete runoff over a rectangular horizontal catchment. This does not size gutters or pipes."}],marks:Array.from({length:outlets},(_,i)=>`Outlet ${i+1} · ${len((i+.5)*spacing,u)} from start`)};}
 const g=pavingRing(v);if(!g)return {errors:["The paver must have a positive inner edge and a joint narrower than its sector. Increase diameter or reduce depth, piece count or joint width."],results:[]};const area=g.area*v.count,volume=area*v.paverThickness;return {diagramValues:{...v,nativeRing:1},results:[{label:"Order quantity",value:`${ceilStable(v.count*(1+v.waste/100))} pavers`,primary:true},{label:"Pavers in ring",value:String(v.count)},{label:"Outer face width",value:len(g.outer,u)},{label:"Inner face width",value:len(g.inner,u)},{label:"Miter from square",value:`${number(180/v.count,4)}°`},{label:"Clear opening across flats",value:len(2*g.innerApothem,u)},{label:"Inner corner diameter",value:len(2*Math.hypot(g.innerApothem,g.inner/2),u)},{label:"Net paver face area",value:`${number(area/(u==="metric"?1e6:144))} ${u==="metric"?"m²":"ft²"}`},{label:"Net paver volume",value:`${number(volume/(u==="metric"?1e9:1728),5)} ${u==="metric"?"m³":"ft³"}`},{label:"Stock blank required",value:`${len(g.outer,u)} × ${len(v.unitDepth,u)} × ${len(v.paverThickness,u)}, plus kerf`}],marks:Array.from({length:v.count},(_,i)=>{const angle=i*2*g.half,r=(g.apothem+g.innerApothem)/2;return `Paver ${i+1} · centre X ${len(-r*Math.sin(angle),u)}, Y ${len(r*Math.cos(angle),u)} · rotation ${number(i*360/v.count)}°`;})};
 }};
}
