"use client";
import { EMPTY_CLIENT_FORM, useClientsBook } from "./_lib/useClientsBook";
export type { SavedClient } from "./_lib/useClientsBook";
export function ClientsManager(){
 const {clients,shared,search,setSearch,form,setForm,error,notice,busy,loaded,save,visible}=useClientsBook();const empty=EMPTY_CLIENT_FORM;
 return <div className="mt-8 space-y-6"><p className="text-sm text-ink-300">{shared?'Shared with your active team. Team members can add and update these contacts.':'Your private address book. Save clients here or when you send a quote.'}</p>{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}{notice&&<p role="status" className="text-sm text-green-300">{notice}</p>}
 <details className="t2q-card-pro p-5" open={!!form.id||clients.length===0}><summary className="min-h-11 cursor-pointer text-lg font-semibold">{form.id?'Edit client':'Add a client'}</summary><form onSubmit={save} className="mt-3 grid gap-4 sm:grid-cols-2">{(['name','email','phone','address'] as const).map(k=><label key={k} className="text-sm capitalize">{k}<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} required={k==='name'} type={k==='email'?'email':k==='phone'?'tel':'text'} maxLength={k==='name'?150:k==='email'?254:k==='phone'?100:500} className="mt-2 min-h-11 w-full rounded-xl border border-white/15 bg-black/20 px-3 text-white"/></label>)}<div className="flex gap-3 sm:col-span-2"><button disabled={busy} className="t2q-btn-primary-pro">{busy?'Saving…':'Save client'}</button>{form.id&&<button type="button" onClick={()=>setForm(empty)} className="t2q-btn-ghost-pro">Cancel edit</button>}</div></form></details>
 <label className="block"><span className="sr-only">Search clients</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email, phone or address" className="min-h-12 w-full rounded-xl border border-white/15 bg-black/20 px-4 text-sm"/></label>
 {!loaded&&!error&&<p role="status">Loading clients…</p>}{loaded&&visible.length===0&&<p className="t2q-card-pro p-8 text-center text-sm text-ink-300">{clients.length?'No matching clients.':'No clients yet. Add your first contact above.'}</p>}
 <div className="grid gap-3 sm:grid-cols-2">{visible.map(c=><article key={c.id} className="t2q-card-pro flex items-start justify-between gap-3 p-5"><div className="min-w-0"><h2 className="font-semibold">{c.name}</h2><p className="mt-2 break-all text-sm text-ink-300">{c.email}<br/>{c.phone}</p><p className="mt-2 text-sm text-ink-400">{c.address}</p></div><button className="min-h-11 shrink-0 text-sm text-brand" onClick={()=>{setForm({id:c.id,name:c.name,email:c.email??'',phone:c.phone??'',address:c.address??''});window.scrollTo({top:0,behavior:'smooth'});}}>Edit</button></article>)}</div>{clients.length===1000&&<p className="text-xs text-ink-400">Showing the first 1,000 clients.</p>}</div>;
}
